name: Build and deploy ASP.Net Core app to Azure Web App - vnetappsqldemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Clean and build
        run: |
          dotnet clean
          dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -r linux-x64 --self-contained -o ${{env.DOTNET_ROOT}}/myapp

      - name: dotnet install ef
        run: dotnet tool install -g dotnet-ef --version 7.0.14
 
      - name: Check and Create Directory
        run: |
          $dir = "${{env.DOTNET_ROOT}}/myapp/DotNetCoreSqlDb"
          if (Test-Path -Path $dir) {
              Write-Host "Directory already exists: $dir"
          } else {
              New-Item -ItemType Directory -Path $dir
              Write-Host "Directory created: $dir"
          }
        shell: pwsh

      - name: dotnet bundle migration
        run: |
         cd ${{env.DOTNET_ROOT}}/myapp
         dotnet ef migrations bundle --runtime linux-x64 -p DotNetCoreSqlDb/DotNetCoreSqlDb.csproj -o migrate

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5ACA5291717C4A57A8AA292958737F38 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5147EB1201E84B0790CF0BE65A99DB38 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9EAE16DF596C4DB7B6520F565553807E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vnetappsqldemo'
          slot-name: 'Production'
          package: .
